[build]
builder = "NIXPACKS"

[deploy]
startCommand = "flask db upgrade && gunicorn wsgi:app --workers 4 --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10 